export enum Status {
    PENDING = "PENDING",
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE",
    APPROVED = 'APPROVED',
    DENIED = 'DENIED',
}

export enum DayInWeek {
    MONDAY = "MONDAY",
    TUESDAY = "TUESDAY",
    WEDNESDAY = "WEDNESDAY",
    THURSDAY = "THURSDAY",
    FRIDAY = "FRIDAY",
    SATURDAY = "SATURDAY",
    SUNDAY = "SUNDAY",
}

export enum Shift {
    MORNING = "MORNING",
    AFTERNOON = "AFTERNOON",
    ALL_DAY = "ALLDAY",
}

export enum ReportReason {
    SPAM = 'SPAM',
    INAPPROPRIATE_CONTENT = 'INAPPROPRIATE CONTENT',
    ABUSIVE_BEHAVIOR = 'ABUSIVE BEHAVIOR',
    FALSE_INFORMATION = 'FALSE INFORMATION',
    HARASSMENT = 'HARASSMENT',
    DISCRIMINATION = 'DISCRIMINATION',
    VIOLATION_OF_TERMS = 'VIOLATION OF TERMS'
}

export enum AppointmentStatus {
    PENDING = "PENDING",
    DONE = "DONE",
    CANCELED = "CANCELED",
}

export enum VietnamCities {
    HaNoi = "Hà Nội",
    HoChiMinh = "Thành phố Hồ Chí Minh",
    ThuDuc = "Thành phố Thủ Đức",
    HaiPhong = "Hải Phòng",
    DaNang = "Đà Nẵng",
    CanTho = "Cần Thơ",
    BienHoa = "Biên Hòa",
    NhaTrang = "Nha Trang",
    Hue = "Huế",
    VungTau = "Vũng Tàu",
    QuyNhon = "Quy Nhơn",
    RachGia = "Rạch Giá",
    LongXuyen = "Long Xuyên",
    ThaiNguyen = "Thái Nguyên",
    NamDinh = "Nam Định",
    PhanThiet = "Phan Thiết",
    CaMau = "Cà Mau",
    BuonMaThuot = "Buôn Ma Thuột",
    ThaiBinh = "Thái Bình",
    Vinh = "Vinh",
    HaLong = "Hạ Long",
    Pleiku = "Pleiku",
    ThanhHoa = "Thanh Hóa",
    HaiDuong = "Hải Dương",
    TamKy = "Tam Kỳ",
    BenTre = "Bến Tre",
    VinhLong = "Vĩnh Long",
    PhuQuoc = "Phú Quốc",
    TraVinh = "Trà Vinh",
    MyTho = "Mỹ Tho",
    BacNinh = "Bắc Ninh",
    LangSon = "Lạng Sơn",
    DongHoi = "Đồng Hới",
    SaDec = "Sa Đéc",
    CaoLanh = "Cao Lãnh",
    BacGiang = "Bắc Giang",
    LaoCai = "Lào Cai",
    DongHa = "Đông Hà",
    MocChau = "Mộc Châu",
    HaTinh = "Hà Tĩnh",
    SonLa = "Sơn La",
    BacKan = "Bắc Kạn",
    PhanRangThapCham = "Phan Rang-Tháp Chàm",
    CamRanh = "Cam Ranh",
    BacLieu = "Bạc Liêu",
    KonTum = "Kon Tum",
    SonTay = "Sơn Tây",
    SocTrang = "Sóc Trăng",
    VinhYen = "Vĩnh Yên",
    DienBienPhu = "Điện Biên Phủ",
    HaGiang = "Hà Giang",
    TamDiep = "Tam Điệp",
    YenBai = "Yên Bái",
    TuyenQuang = "Tuyên Quang",
    PhuLy = "Phủ Lý",
    HoaBinh = "Hòa Bình",
    HungYen = "Hưng Yên",
    BinhDuong = "Bình Dương",
    BinhPhuoc = "Bình Phước",
    HaNam = "Hà Nam",
    NinhBinh = "Ninh Bình",
    TayNinh = "Tây Ninh",
    QuangNgai = "Quảng Ngãi",
    QuangTri = "Quảng Trị",
    QuangBinh = "Quảng Bình",
    DakNong = "Đắk Nông",
    DakLak = "Đắk Lắk",
    GiaLai = "Gia Lai",
    LamDong = "Lâm Đồng",
    AnGiang = "An Giang",
    TienGiang = "Tiền Giang",
    BinhThuan = "Bình Thuận",
    KhanhHoa = "Khánh Hòa",
    PhuYen = "Phú Yên",
    BinhDinh = "Bình Định",
    HauGiang = "Hậu Giang",
    KienGiang = "Kiên Giang",
    DongThap = "Đồng Tháp",
    VinhPhuc = "Vĩnh Phúc",
    DienBien = "Điện Biên",
    LaiChau = "Lai Châu",
    QuangNinh = "Quảng Ninh",
    PhuTho = "Phú Thọ",
    CaoBang = "Cao Bằng",
}

